apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "spree.fullname" . }}
  labels:
    app: {{ template "spree.name" . }}
    chart: {{ template "spree.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "spree.name" . }}
      release: {{ .Release.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ template "spree.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MYSQL_DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: spree
                  key: host
            - name: MYSQL_DATABASE_USER_NAME
              valueFrom:
                configMapKeyRef:
                  name: spree
                  key: username
            - name: MYSQL_DATABASE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: spree
                  key: username
          ports:
          - containerPort: 3000
            protocol: TCP
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
