adminUser: admin
adminPassword: admin
ingress:
  enabled: true
  hosts:
    - grafana.test.mickey-kubernetes.com
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources: 
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server.monitoring.svc.cluster.local
      access: proxy
      isDefault: true
    - name: Cloudwatch
      type: cloudwatch
      jsonData:
        defaultRegion: us-east-1
        authType: keys
      secureJsonData:
        accessKey: "AKIAJESINM4VUGSA32TQ"
        secretKey: "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"
dashboards:
  kubernetes-prometheus:
    gnetId: 1621
    revision: 1
    datasource: Prometheus
  kubernetes-deployment:
    gnetId: 741
    revision: 1
    datasource: Prometheus
  kubernetes-nginx:
    gnetId: 3050
    revision: 1
    datasource: Prometheus
  aws-rds:
    gnetId: 702
    revision: 1
    datasource: Cloudwatch
  aws-asg:
    gnetId: 677
    revision: 3
    datasource: Cloudwatch
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards