adminUser: admin
adminPassword: admin
ingress:
  enabled: true
  hosts:
    - grafana.test.mickey-kubernetes.com
  annotations:
    kubernetes.io/ingress.class: nginx
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources: 
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server.monitoring.svc.cluster.local
      access: proxy
      isDefault: true
dashboards:
  kubernetes-prometheus:
    gnetId: 1621
    revision: 1
    datasource: Prometheus
  kubernetes-deployment:
    gnetId: 741
    revision: 1
    datasource: Prometheus
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards