ingress:
  enabled: true
  path: /
  hosts:
    - spree.test.mickey-kubernetes.com
hpa:
  enabled: true
  maxreplicas: 10
  minreplicas: 2
  targetCPUUtilizationPercentage: 50
resources:
  requests:
    cpu: "100m"