ingress:
  enabled: true
  path: /
  hosts:
    - spree.test.mickey-kubernetes.com
hpa:
  enabled: true
  maxreplicas: 10
  minreplicas: 2
  targetCPUUtilizationPercentage: 50
resources:
  requests:
    cpu: "100m"
configmap:
  host: spree.ce4t98bbt7zi.us-east-1.rds.amazonaws.com
  username: admin
  password: admin123
image:
  repository: firedocker/spree
  tag: latest