apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: spree
  namespace: spree
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: spree
  targetCPUUtilizationPercentage: 50
